# these are executed in order.  each must pass for the next to be run
stages:
  - lint
  # - test
  - deploy

  # defaults
language: node_js
node_js: '10'
# disable automatic npm install
install: true

jobs:
  include:
    - stage: lint
      script: bash .travis.sh install lint
      node_js: '10'

    # No tests as of now
    #- &node
    #  stage: test
    #  script: bash .travis.sh install build
    #  node_js: '8'

      # includes testing, thats why v10 is not in test stage
    - stage: deploy
      script: bash .travis.sh install build deploy
      node_js: '10'

  env:
  global:
    secure: "ty9ht6c1+/z2nZuTM4ceXgewwkK9XFcqytfSsoKdqqbxExv6Z3vkC5RqxmfxjJp88K2545tFC81sPySQJTtZsBS/9cluQNemM7J8pmi0aCS1Rph/vykNdy/IruVI4utWXmVuVyJlPwCgnBPcMErTaClL0t1432UOPJTRQxuYXOpdaZtAr+0qHAxiJ7Yny7hcFqiV5baRZMk32bBK5NCZJ4CDuCYrHeH31IDC4B8mrqtGVRuJeAOIFLAo4j4L1S8IwbtRkqcjoVkrUe8wsf8Ia2v7IxT+wzP2IZADr1t8C9VC22tFfcBE+HJTegTSqMvsenGSNwZII/Yl1o6t7MeAxHCbHhGNpRqom/SwZLzMciwmjAHXU5rMQnTuWpxVyE0+WzK+7sgiPfIDoiBm8TLS9n1H2YLnPQBZ6kglptLNoDJmWFoPTZMSe9pbGl+3bsKFC1xmgT1qTFQVe5YJXPmsPAOvwHtw50+A9A7LIrFUpPQr6zSpWGo+1Cp1YAheALd/sW007k2BW0JZ7I05hV1ePgmDpWqxXxumuEbymCs56D7XdcIitTmAv5B78SMUhaadBshSkxp1g5V0PU1ZqDBkR63jIxUdnbTmcE3gIXh52iP6zF/TZgMNDDPOuF4vlc6soKeg/L5d8JM+uST4F0HqtAIvvap4PSQJt1hUeg2n/IA="
